"""sixth Migration

Revision ID: 192ba66c5aa4
Revises: 656dea991cc4
Create Date: 2022-05-10 12:39:24.594511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192ba66c5aa4'
down_revision = '656dea991cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_pitch_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'pitch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_pitch_id_fkey', 'users', 'pitches', ['pitch_id'], ['id'])
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'user_id')
    # ### end Alembic commands ###
