"""fifth Migration

Revision ID: 656dea991cc4
Revises: 20a0767e57a3
Create Date: 2022-05-10 12:31:49.565244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656dea991cc4'
down_revision = '20a0767e57a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'pitches', ['pitch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'pitch_id')
    # ### end Alembic commands ###
