"""seventh Migration

Revision ID: bd9380e0a970
Revises: 192ba66c5aa4
Create Date: 2022-05-10 13:59:33.127967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd9380e0a970'
down_revision = '192ba66c5aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downvotes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'downvotes', 'users', ['user_id'], ['id'])
    op.add_column('upvotes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'upvotes', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('password_secure', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'password_secure')
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.drop_column('upvotes', 'user_id')
    op.drop_constraint(None, 'downvotes', type_='foreignkey')
    op.drop_column('downvotes', 'user_id')
    # ### end Alembic commands ###
