"""ninth Migration

Revision ID: deab40c8ce3c
Revises: 3d8d1d958a2a
Create Date: 2022-05-10 19:49:47.382385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deab40c8ce3c'
down_revision = '3d8d1d958a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('post', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'post')
    # ### end Alembic commands ###
